default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: etude_development

test:
  <<: *default
  database: etude_test

production:
  <<: *default
  database: etude_production
  username: etude
  password: <%= ENV["ETUDE_DATABASE_PASSWORD"] %>
