default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['POSTGRES_USER'] %>

development:
  <<: *default
  database: <%= ENV['POSTGRES_NAME'] %>_development
  host: localhost

test:
  <<: *default
  database: <%= ENV['POSTGRES_NAME'] %>_test
  passwrod: <%= ENV['POSTGRES_PASSWORD'] %>
  host: localhost

production:
  <<: *default
  database: <%= ENV['POSTGRES_NAME'] %>_production
