default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['POSTGRES_USER'] %>
  port: 5432

development:
  <<: *default
  database: <%= ENV['POSTGRES_NAME'] %>
  host: 127.0.0.1

test:
  <<: *default
  database: <%= ENV['POSTGRES_NAME'] %>
  passwrod: <%= ENV['POSTGRES_PASSWORD'] %>
  host: 127.0.0.1

production:
  <<: *default
  database: <%= ENV['POSTGRES_NAME'] %>
